---
name: on commit
run-name: on commit
on:
    push
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: creating environment
          run: |
            echo "Lets install dependencies! yey"
            sudo apt update
            if [ $? -eq 0 ]; then
              echo "Apt up-to-date"
              sudo apt install python3
            else
              echo "Ubuntu is a shit"
            fi


