---
name: on commit
run-name: on commit
on:
    push
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: creating environment
          run: |
            echo "hola"
