---
name: on commit
run-name: on commit
on:
    push
jobs:
    test:
      runs-on: ubuntu-latest
      container: 
        image: josepepedev/pytest:latest
      steps:
        - uses: actions/checkout@v3

        - name: run unit-testing
          run: |
            python3 -m pytest
            if [ $? -eq 0 ]; then
             echo "Yey! Unittesting passed. Lets merge"
              exit 0
            else
              echo "Your code is garbage, refusing to merge it"
              exit 1
            fi
